<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matthew Ivory">

<title>Statistics for Social Scientists - 9. ANOVA and linear regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../Worksheets/Answers/Worksheet_wk1_Answers.html" rel="next">
<link href="../Worksheets/Worksheet_wk8.html" rel="prev">
<link href="../Images/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script language="JavaScript" type="text/javascript" src="../function.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../include/webex.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Statistics for Social Scientists</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../Worksheets/Worksheet_wk1.html" rel="" target="" aria-current="page">
 <span class="menu-text">Week 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Worksheets/Worksheet_wk2.html" rel="" target="">
 <span class="menu-text">Week 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Worksheets/Worksheet_wk3.html" rel="" target="">
 <span class="menu-text">Week 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Worksheets/Worksheet_wk4.html" rel="" target="">
 <span class="menu-text">Week 4</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Worksheets/Worksheet_wk5.html" rel="" target="">
 <span class="menu-text">Week 5</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Worksheets/Worksheet_wk6.html" rel="" target="">
 <span class="menu-text">Week 6</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Worksheets/Worksheet_wk7.html" rel="" target="">
 <span class="menu-text">Week 7</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Worksheets/Worksheet_wk8.html" rel="" target="">
 <span class="menu-text">Week 8</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Worksheets/Worksheet_wk9.html" rel="" target="">
 <span class="menu-text">Week 9</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Worksheets/Worksheet_wk1.html">Worksheets</a></li><li class="breadcrumb-item"><a href="../Worksheets/Worksheet_wk9.html">9. ANOVA and linear regression</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Worksheets</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Worksheets/Worksheet_wk1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Introduction to quantitative research methods using R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Worksheets/Worksheet_wk2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Data management and data wrangling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Worksheets/Worksheet_wk3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Exploratory Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Worksheets/Worksheet_wk4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Data visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Worksheets/Worksheet_wk5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Live Data Wrangling Walkthrough</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Worksheets/Worksheet_wk6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Probability and distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Worksheets/Worksheet_wk7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Tests for discrete variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Worksheets/Worksheet_wk8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Correlations and t-tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Worksheets/Worksheet_wk9.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">9. ANOVA and linear regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Answersheets</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Worksheets/Answers/Worksheet_wk1_Answers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Introduction to quantitative research methods using R - Answers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Worksheets/Answers/Worksheet_wk2_Answers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Data management and data wrangling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Worksheets/Answers/Worksheet_wk3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Exploratory Data Analysis - Answers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Worksheets/Answers/Worksheet_wk4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Data visualization</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#references-for-this-handout" id="toc-references-for-this-handout" class="nav-link active" data-scroll-target="#references-for-this-handout">References for this handout</a></li>
  <li><a href="#task-0-setting-up-our-environment" id="toc-task-0-setting-up-our-environment" class="nav-link" data-scroll-target="#task-0-setting-up-our-environment">Task 0: Setting up our environment</a></li>
  <li><a href="#task-1-between-participant-anova" id="toc-task-1-between-participant-anova" class="nav-link" data-scroll-target="#task-1-between-participant-anova">Task 1: Between-participant ANOVA</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#visualising" id="toc-visualising" class="nav-link" data-scroll-target="#visualising">Visualising</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a></li>
  </ul></li>
  <li><a href="#task-2-within-participant-anova" id="toc-task-2-within-participant-anova" class="nav-link" data-scroll-target="#task-2-within-participant-anova">Task 2: Within-participant ANOVA</a></li>
  <li><a href="#task-3-linear-regression" id="toc-task-3-linear-regression" class="nav-link" data-scroll-target="#task-3-linear-regression">Task 3: Linear regression</a>
  <ul class="collapse">
  <li><a href="#data-tidying" id="toc-data-tidying" class="nav-link" data-scroll-target="#data-tidying">Data Tidying</a></li>
  <li><a href="#data-visualisation" id="toc-data-visualisation" class="nav-link" data-scroll-target="#data-visualisation">Data Visualisation</a></li>
  <li><a href="#conducting-a-linear-regression" id="toc-conducting-a-linear-regression" class="nav-link" data-scroll-target="#conducting-a-linear-regression">Conducting a linear regression</a></li>
  <li><a href="#checking-assumptions" id="toc-checking-assumptions" class="nav-link" data-scroll-target="#checking-assumptions">Checking assumptions</a></li>
  <li><a href="#effect-sizes" id="toc-effect-sizes" class="nav-link" data-scroll-target="#effect-sizes">Effect sizes</a></li>
  <li><a href="#writing-up-a-linear-regression-result" id="toc-writing-up-a-linear-regression-result" class="nav-link" data-scroll-target="#writing-up-a-linear-regression-result">Writing up a linear regression result</a></li>
  </ul></li>
  <li><a href="#task-4-proof-anova-linear-regression" id="toc-task-4-proof-anova-linear-regression" class="nav-link" data-scroll-target="#task-4-proof-anova-linear-regression">Task 4: Proof: ANOVA == Linear Regression</a></li>
  <li><a href="#other" id="toc-other" class="nav-link" data-scroll-target="#other">Other</a>
  <ul class="collapse">
  <li><a href="#the-trout-anova-example-from-the-slides" id="toc-the-trout-anova-example-from-the-slides" class="nav-link" data-scroll-target="#the-trout-anova-example-from-the-slides">The trout ANOVA example from the slides</a></li>
  <li><a href="#the-house-regression-example" id="toc-the-house-regression-example" class="nav-link" data-scroll-target="#the-house-regression-example">The house regression example</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/M1V0/FASS512/edit/main/Worksheets/Worksheet_wk9.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/M1V0/FASS512/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">9. ANOVA and linear regression</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Matthew Ivory </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>Three important things to remember:</p>
<ol type="1">
<li><p>As you complete the handout, please don’t just read the commands, please type every single one of them. This is really important: Learning to program is like practicing a conversation in a new language. You will improve gradually, but only if you practice.</p></li>
<li><p>If you’re stuck with something, please write down your questions (to share later in class) and try to solve the problem. Please ask your group members for support and, conversely, if another student is stuck, please try to help them out, too. This way, we develop a supportive learning environment that benefits everybody. In addition, get used to the Help pages in RStudio and start finding solutions online (discussion forums, online textbooks, etc.). This is really important, too. You will only really know how to do quantitative research and statistical analyses when you are doing your own research and dealing with your own data. At that point, you need to be sufficiently autonomous to solve problems, otherwise you will end up making very slow progress in your PhD.</p></li>
<li><p>Finally, if you do not complete the handout in class, please complete the handout at home. This is important as we will assume that you know the material covered in this handout. And again, the more you practice the better, so completing these handouts at home is important.</p></li>
</ol>
<section id="references-for-this-handout" class="level3">
<h3 class="anchored" data-anchor-id="references-for-this-handout">References for this handout</h3>
<p>Many of the examples and data files from our class come from these excellent textbooks:</p>
<ul>
<li>Andrews, M. (2021). Doing data science in R. Sage.</li>
<li>Crawley, M. J. (2013). The R book. Wiley.</li>
<li>Fogarty, B. J. (2019). Quantitative social science data with R. Sage.</li>
<li>Winter, B. (2019). Statistics for linguists. An introduction using R. Routledge.</li>
</ul>
</section>
<section id="task-0-setting-up-our-environment" class="level2">
<h2 class="anchored" data-anchor-id="task-0-setting-up-our-environment">Task 0: Setting up our environment</h2>
<p>You should be able to do all these things, if not - check back on previous week’s content as a reminder</p>
<ol type="1">
<li><p>Create a new script and call it Week 9.</p></li>
<li><p>Load in the tidyverse library at the top of the script</p></li>
</ol>
</section>
<section id="task-1-between-participant-anova" class="level2">
<h2 class="anchored" data-anchor-id="task-1-between-participant-anova">Task 1: Between-participant ANOVA</h2>
<p>We aren’t going to spend much time on ANOVA, because as I said in the lecture it is a special case of the linear regression, and I personally believe that while you need to know that ANOVAs exist (because people still use them) you are always better off using the linear model. In fact, to provde their equivalence, I will demonstrate in Task 3 that the same output from the anova is achieved using <code>lm()</code></p>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>read in the file called <code>robo_lab.csv</code> and call the object <code>robot</code>.</p>
<p>This is a “toy” dataset - we’ve come across these before, but essentially it’s synthetic data to drive home an analytical point. Let’s create some context for this dataset called <code>robot</code>. I have decided that teaching could be more effectively done by a robot, rather than myself. So in my spare time I built three different robots designed to teach statistics. But I don’t know which of the three is best. Robot Alpha (A) is pretty bare bones, I designed in first, and built it with scrap materials. Robot Beta (B) has a dopey little face I made. Finally, I learnt how to 3D print more likelike faces, so I built Robot Omega (O) too.</p>
<p><img src="https://images.unsplash.com/photo-1580835239846-5bb9ce03c8c3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;ixlib=rb-1.2.1&amp;auto=format&amp;fit=crop&amp;w=976&amp;q=80" class="img-fluid" alt="Robot A(lpha)"> <img src="https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&amp;cs=tinysrgb&amp;h=750&amp;w=1260" class="img-fluid" alt="Robot B(eta)"> <img src="https://images.unsplash.com/photo-1593376893114-1aed528d80cf?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=958&amp;q=80" class="img-fluid" alt="Robot O(mega)"></p>
<p>From these three different robots, who only differ in physical appearance, I believed that the more likelife the robot, the better students would score on a statistics test, because they would be less scared of the robot. Formally, my hypothesis is “scores would be significantly higher amongst individuals assigned Robot O(mega) than those assigned Robot A(lpha) or B(eta)”.</p>
<p>It was now time to test how the students responded to the robots. In a controlled experiment, the researchers randomly assigned groups of students either Robot A(lpha), Robot B(eta), or Robot O(mega). Note this experiment is one factor (Robot assignment) study made of three levels (Robot A, Robot B, Robot C). Those individuals assigned Robot A(lpha) were denoted as belonging to ‘Group A’.</p>
<p>Those individuals assigned Robot B(eta) were denoted as belonging to ‘Group B’.</p>
<p>Those individuals assigned Robot O(mega) were denoted as beloning to ‘Group O’.</p>
<p>Note. The groups are mutually exclusively - i.e., a participant was assigned to either Group A/Robot A, Group B/Robot B, Group O/Robot O.</p>
<p>Prior to the experiment, independent raters reliably agreed that Robot O(mega) more closely resembled a human being than Robot B(eta) [second closest resemblance] and Robot A(lpha) [lowest resemblance].</p>
<p>The dataset contains three variables: participant ID (<code>ID</code>), Which robot they were taught by (<code>Group</code>), How they rated the robot (<code>Likeability</code>), and their test score (<code>Score</code>).</p>
<p>First things first, let us summarise the data and get a mean and SD for score per group. We will need to use <code>group_by()</code> and <code>summarise()</code>. Assign it to an object called <code>robot_descriptives</code></p>
<p>We can also use <code>max()</code> and <code>min()</code> to get the maximum and minimum scores on the test too.</p>
</section>
<section id="visualising" class="level3">
<h3 class="anchored" data-anchor-id="visualising">Visualising</h3>
<p>Next, let’s have a look at the data in plot form.</p>
<p>First a histogram, noting that I specify an argument <code>bins = 12</code>. Can you look in the help tab and search for <code>geom_histogram</code> to see what bins does?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>robot <span class="sc">|&gt;</span> </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Score)) <span class="sc">+</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Worksheet_wk9_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now a boxplot We can use a boxplot because the Group variable is a factor, it is categorical.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Worksheet_wk9_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="analysis" class="level3">
<h3 class="anchored" data-anchor-id="analysis">Analysis</h3>
<p>To identify whether the differences between groups are statistically significant, we need to perform an Analysis of Variance. First, let’s be sure we have chosen the correct type of ANOVA. We have one factor. This is because we have one Independent Variable (Robot) with three levels (Robot A, B and O). Also, the design is between group, as each participant is assigned to only one robot, and data from only one time point is taken.</p>
<p>To run our one-factor between participants ANOVA, we will use tidyverse’s <code>aov()</code> function. Let’s set ‘Score’ as our first dependent variable of examination. ‘Group’ is then our predictive factor (independent variable). Note, in the code below, the DV and the IV are separated by the ‘~’ character. Please carry out the following command. This also includes requesting a summary and effectsize for our model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>model_robot <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">data =</span> robot, Score <span class="sc">~</span> Group)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_robot) <span class="co">#We ask for a summary of this model. This provides F statistic and P value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Group         2   1223   611.3   12.52 6.77e-06 ***
Residuals   237  11571    48.8                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>For calculating effect sizes for ANOVAs, we use eta-squared, or partial eta-squared. For one-way between subjects designs, partial eta-squared is equivalent to eta-squared. We can calculate this using the function <code>effectsize()</code> from the package <code>effectsize</code>. So install and load effectsize first. effectsize also gives us the confidence intervals of the effect too, but note it is only bounded at the bottom and it gives us a message to say so too.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">effectsize</span>(model_robot) <span class="co"># we ask for an eta2 effect size for our model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>For one-way between subjects designs, partial eta squared is equivalent
  to eta squared. Returning eta squared.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA

Parameter | Eta2 |       95% CI
-------------------------------
Group     | 0.10 | [0.04, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<p>ANOVA effect sizes can be interpreted as:</p>
<p><span class="math inline">\(\eta^2\)</span> = 0.01 indicates a small effect <span class="math inline">\(\eta^2\)</span> = 0.06 indicates a medium effect <span class="math inline">\(\eta^2\)</span> = 0.14 indicates a large effect</p>
<p>Before we move on, realise that we tested three groups and all the ANOVA tells us is that there is a significant difference between groups. But which ones? We need to run additional post-hoc tests to determine the differences.</p>
<p>Post-hoc tests, as mentioned in the lecture, allow us to test each group individually. It is the equivalent (in this case) of running a t-test between each group, but where we have reduced our <em>p</em>-value threshold (acknowledging the issue of multiple comparisons - again see the lecture).</p>
<p>We need to install and load a new library called <code>rstatix</code> first</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstatix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'rstatix'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:effectsize':

    cohens_d, eta_squared</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    filter</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise_t_test</span>(robot,</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  Score <span class="sc">~</span> Group, <span class="co"># indicate this is paired (within participants) data</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span> <span class="co">#adjust for bonferroni correction</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 9
  .y.   group1 group2    n1    n2          p p.signif     p.adj p.adj.signif
* &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;      &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;       
1 Score A      B         80    80 0.0417     *        0.125     ns          
2 Score A      O         80    80 0.00000123 ****     0.0000037 ****        
3 Score B      O         80    80 0.00372    **       0.0111    *           </code></pre>
</div>
</div>
<p>The output from this gives us a lot of new information. Importantly, it breaks down the differences between each group, compares them, and gives us an adjusted p-value, which is adjusted for the multiple comparisons. It also tells us whether or not the new p-value is significant or not. In this case, we can see that groups A &amp; B are not significantly different, A &amp; O are, and B &amp; O are too. So the most lifelike robot leads to greater test scores, and A and B are not significantly different, perhaps because they’re both too robot-y.</p>
<p>Right, we’ve covered a lot of analysis and now we need to gather all the relevant information together for reporting the ANOVA results in APA format. To do this, let’s run all the outputs together so we can identify all the necessary values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>robot_descriptives</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  Group  mean    SD
  &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;
1 A      58.1  6.45
2 B      60.4  7.27
3 O      63.6  7.22</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_robot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Group         2   1223   611.3   12.52 6.77e-06 ***
Residuals   237  11571    48.8                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">effectsize</span>(model_robot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>For one-way between subjects designs, partial eta squared is equivalent
  to eta squared. Returning eta squared.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA

Parameter | Eta2 |       95% CI
-------------------------------
Group     | 0.10 | [0.04, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise_t_test</span>(robot,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  Score <span class="sc">~</span> Group, <span class="co"># indicate this is paired (within participants) data</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span> <span class="co">#adjust for bonferroni correction</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 9
  .y.   group1 group2    n1    n2          p p.signif     p.adj p.adj.signif
* &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;      &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;       
1 Score A      B         80    80 0.0417     *        0.125     ns          
2 Score A      O         80    80 0.00000123 ****     0.0000037 ****        
3 Score B      O         80    80 0.00372    **       0.0111    *           </code></pre>
</div>
</div>
<p>And now to answer questions on the values we have</p>
<ol type="1">
<li><p>What are the degrees of freedom of the ANOVA? Reported as “(X, Y)”. (<input class="webex-solveme nospaces" size="1" data-answer="[&quot;2&quot;]">, <input class="webex-solveme nospaces" size="3" data-answer="[&quot;237&quot;]">)</p></li>
<li><p>What is the F-value? <input class="webex-solveme nospaces" size="5" data-answer="[&quot;12.52&quot;]"></p></li>
<li><p>What is the <em>p</em>-value? Report this as 3 decimal places, unless it is under .001, in which case report “&lt; .001”. <em>p</em> <select class="webex-select"><option value="blank"></option><option value="">=</option><option value="answer">&lt;</option></select> <input class="webex-solveme nospaces" size="5" data-answer="[&quot;0.001&quot;,&quot;.001&quot;]"></p></li>
<li><p>Is this a significant model? <select class="webex-select"><option value="blank"></option><option value="answer">yes</option><option value="">no</option></select></p></li>
<li><p>What is the effect size, reported to 2dp? <input class="webex-solveme nospaces" size="3" data-answer="[&quot;0.1&quot;,&quot;.1&quot;]"></p></li>
<li><p>What is the adjusted <em>p</em>-value for group A &amp; B? Again to 3dp unless it is under .001, in which case report “&lt; .001”. <em>p</em> <select class="webex-select"><option value="blank"></option><option value="">&lt;</option><option value="answer">=</option></select> <input class="webex-solveme nospaces" size="5" data-answer="[&quot;0.125&quot;,&quot;.125&quot;]"></p></li>
<li><p>What is the adjusted <em>p</em>-value for group A &amp; O? Again to 3dp unless it is under .001, in which case report “&lt; .001”. <em>p</em> <select class="webex-select"><option value="blank"></option><option value="">=</option><option value="answer">&lt;</option></select> <input class="webex-solveme nospaces" size="5" data-answer="[&quot;0.001&quot;,&quot;.001&quot;]"></p></li>
<li><p>What is the adjusted <em>p</em>-value for group B &amp; O? Again to 3dp unless it is under .001, in which case report “&lt; .001”. <em>p</em> <select class="webex-select"><option value="blank"></option><option value="">&lt;</option><option value="answer">=</option></select> <input class="webex-solveme nospaces" size="5" data-answer="[&quot;0.011&quot;,&quot;.011&quot;]"></p></li>
</ol>
<p>Great. Now we need to write this in a fashion suitable for a report. Pay attention to where each value goes.</p>
<p>A one-factor between-participants ANOVA revealed that test scores were significantly different between our robot groups (Robot A M = 58.10, SD = 6.45, Robot B M = 60.36, SD = 7.27; Robot O M = 63.60, SD = 7.22), F(2,237) = 12.52, p &lt; .001, η2 = 0.10. Posthoc tests using bonferroni correction found that group O yielded significantly higher scores than group A (<em>p</em><sub>adj</sub> &lt; .001), as well as higher scores than group B (<em>p</em><sub>adj</sub> &lt; .011). No significant difference was seen between groups A and B (<em>p</em><sub>adj</sub> = .125). This suggests that the more likelike robot Omega produces significantly higher test scores than robots Alpha and Beta.</p>
</section>
</section>
<section id="task-2-within-participant-anova" class="level2">
<h2 class="anchored" data-anchor-id="task-2-within-participant-anova">Task 2: Within-participant ANOVA</h2>
<p>So that was a between-participant ANOVA, where participants were only in one group. Not both. Now what if we wated to test how a factor can influence a participant. Perhaps levels of self-esteem over three different time points.</p>
<p>We can find this data in the <code>datarium</code> package, so another one to install! We don’t need to load it when we then run this next command</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"selfesteem"</span>, <span class="at">package =</span> <span class="st">"datarium"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>selfesteem</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
      id    t1    t2    t3
   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1     1  4.01  5.18  7.11
 2     2  2.56  6.91  6.31
 3     3  3.24  4.44  9.78
 4     4  3.42  4.71  8.35
 5     5  2.87  3.91  6.46
 6     6  2.05  5.34  6.65
 7     7  3.53  5.58  6.84
 8     8  3.18  4.37  7.82
 9     9  3.51  4.40  8.47
10    10  3.04  4.49  8.58</code></pre>
</div>
</div>
<p>Currently the data is in what is called <code>wide</code> format. We have a participant per row, and we have all their data associated in different columns. For a lot of analyses, we are better off with a <code>long</code> format or <code>tidy</code> format. For tidy data, each row represents a single observation, and the observations are grouped together into cases based on the value of a variable. Sounds confusing, let’s run some code that does this for us, and have a look at what changes</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>selfesteem_long <span class="ot">&lt;-</span> selfesteem <span class="sc">|&gt;</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> t1<span class="sc">:</span>t3, <span class="at">names_to =</span> <span class="st">"time"</span>, <span class="at">values_to =</span> <span class="st">"score"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>selfesteem_long</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 3
      id time  score
   &lt;int&gt; &lt;chr&gt; &lt;dbl&gt;
 1     1 t1     4.01
 2     1 t2     5.18
 3     1 t3     7.11
 4     2 t1     2.56
 5     2 t2     6.91
 6     2 t3     6.31
 7     3 t1     3.24
 8     3 t2     4.44
 9     3 t3     9.78
10     4 t1     3.42
# ℹ 20 more rows</code></pre>
</div>
</div>
<p>Compute some descriptive statistics like above and save it to a object called <code>selfesteem_descriptives</code>. Don’t forget to group by time</p>
<p>Create a boxplot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>selfesteem_long <span class="sc">|&gt;</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(time, score)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Worksheet_wk9_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Looks like we can expect a pretty big difference in self-esteem over time!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>model_selfesteem <span class="ot">&lt;-</span> <span class="fu">anova_test</span>(<span class="at">data =</span> selfesteem_long, <span class="at">dv =</span> score, <span class="at">wid =</span> id, <span class="at">within =</span> time)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">get_anova_table</span>(model_selfesteem)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA Table (type III tests)

  Effect DFn DFd      F        p p&lt;.05   ges
1   time   2  18 55.469 2.01e-08     * 0.829</code></pre>
</div>
</div>
<p>The self-esteem score was statistically significantly different at the different time points during the diet, F(2, 18) = 55.5, p &lt; 0.0001, eta2[g] = 0.83.</p>
<ul>
<li>F Indicates that we are comparing to an F-distribution (F-test); (2, 18) indicates the degrees of freedom in the numerator (DFn) and the denominator (DFd), respectively; 55.5 indicates the obtained F-statistic value</li>
<li>p specifies the p-value</li>
<li>ges is the generalized effect size (amount of variability due to the within-subjects factor) - eta-squared</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise_t_test</span>(selfesteem_long,</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  score <span class="sc">~</span> time, <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 10
  .y.   group1 group2    n1    n2 statistic    df           p p.adj p.adj.signif
* &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;       
1 score t1     t2        10    10     -4.97     9 0.000772     2e-3 **          
2 score t1     t3        10    10    -13.2      9 0.000000334  1e-6 ****        
3 score t2     t3        10    10     -4.87     9 0.000886     3e-3 **          </code></pre>
</div>
</div>
<p>All the pairwise differences are statistically significant.</p>
<p>How would you write this up? Give it a go</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The self-esteem score was statistically significantly different at the different time points, F(2, 18) = 55.5, p &lt; 0.0001, generalized eta squared = 0.82. Post-hoc analyses with a Bonferroni adjustment revealed that all the pairwise differences, between time points, were statistically significantly different (p &lt;= 0.05).</p>
</div>
</div>
</div>
<p>Brilliant. We breezed through this second ANOVA because it is similar to the first but it just uses some different functions to arrive at the same point. The output values are the same type, just formatted differently.</p>
<p>You will note that we didn’t really check the assumptions of our ANOVAs</p>
</section>
<section id="task-3-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="task-3-linear-regression">Task 3: Linear regression</h2>
<p>This is taken from Glasgow’s excellent PsyTeachR materials.</p>
<p>We are analysising responses from the STARS Statistics Anxiety Survey. It was administered to students in the third-year statistics course in Psychology at the University of Glasgow. All responses are anonymised.</p>
<p>“The STARS survey (Cruise, Cash, &amp; Bolton, 1985<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>) is a 51-item questionnaire, with each response on a 1 to 5 scale, with higher numbers indicating greater anxiety.”</p>
<p>It looks something like:</p>
<p><a href="images/week9_1.png">Example STARS items</a></p>
<p>Using data from attendance at weekly drop-in sessions for extra support, let’s see whether a relationship between attendance and anxiety exists. We would expect that greater attendance of sessions results in lower statistical anxiety</p>
<p>We hypothesise that increased drop-in session attendance results in reduced anxiety scores.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 37 Columns: 52
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (52): ID, Q01, Q02, Q03, Q04, Q05, Q06, Q07, Q08, Q09, Q10, Q11, Q12, Q1...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 100 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (2): ID, n_weeks

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<section id="data-tidying" class="level3">
<h3 class="anchored" data-anchor-id="data-tidying">Data Tidying</h3>
<p>We want to read in the two datafiles (L3_stars.csv, psess.csv) called <code>stars</code> and <code>engage</code> respectively.</p>
<p>Have an explore of the data. The ID column is shared across the datasets (remember we experienced something similar last week), and the variable n_weeks in the psess.csv file tells you how many (out of eight) a given student attended. The rest of the data in <code>stars</code> are the results of the test.</p>
<p>Our next step is to calculate a mean anxiety score for each student. We currently have 51 different answers to the scale items, and we just need one value per participant.</p>
<p>Currently the data is in what is called <code>wide</code> format. We have a participant per row, and we have all their data associated in different columns. For a lot of analyses, we are better off with a <code>long</code> format or <code>tidy</code> format. For tidy data, each row represents a single observation, and the observations are grouped together into cases based on the value of a variable. Sounds confusing, let’s run some code that does this for us, and have a look at what changes</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>stars_long <span class="ot">&lt;-</span> stars <span class="sc">|&gt;</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> Q01<span class="sc">:</span>Q51, <span class="at">names_to =</span> <span class="st">"Question"</span>, <span class="at">values_to =</span> <span class="st">"Score"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stars_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
     ID Question Score
  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;
1     3 Q01          1
2     3 Q02          1
3     3 Q03          1
4     3 Q04          1
5     3 Q05          1
6     3 Q06          1</code></pre>
</div>
</div>
<p>What changed? We went from a 37x52 dataset, to a 1887x3 dataset, where we now have ID as one column, Question (which was the columns going Q01, Q02,…, Q51) and the values from those columns in the Score column. We converted from a wide to a long format.</p>
<p>The convenience of having a long (or tidy) format is that we can calculate statistics (like means and SDs) far more conveniently.</p>
<p>In the code chunk below, replace the <code>***</code> with the right variables</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>stars_mean <span class="ot">&lt;-</span> stars_long <span class="sc">|&gt;</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">|&gt;</span> <span class="co">#remove any non-responses</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="sc">**</span><span class="er">*</span>) <span class="sc">|&gt;</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_anxiety =</span> <span class="fu">mean</span>(<span class="sc">**</span><span class="er">*</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The next step is to join the two datasets together (<code>stars_mean</code> and <code>engage</code>) using <code>inner_join()</code> which we used in last week’s worksheet. Using the same code structure as last week, but replacing the variables as needed, can you get the same output below saved to an object called <code>data</code>?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 37 × 3
      ID mean_anxiety n_weeks
   &lt;dbl&gt;        &lt;dbl&gt;   &lt;dbl&gt;
 1     3         1.06       5
 2     7         2.71       2
 3    12         2.24       3
 4    16         2.86       2
 5    23         1.71       6
 6    29         1.80       7
 7    39         1.96       2
 8    42         2.24       7
 9    43         2.69       5
10    44         1.92       4
# ℹ 27 more rows</code></pre>
</div>
</div>
<p>We can also run the below to get descriptive statistics for the overall sample. This can be useful for a future writeup of the research. Run the following code to get an easy summary of the data, make sure you understand what each line does and how it corresponds to the output</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>descriptives <span class="ot">&lt;-</span> data  <span class="sc">|&gt;</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_anx =</span> <span class="fu">mean</span>(mean_anxiety, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_anx =</span> <span class="fu">sd</span>(mean_anxiety, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_weeks =</span> <span class="fu">mean</span>(n_weeks, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_weeks =</span> <span class="fu">sd</span>(n_weeks, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-visualisation" class="level3">
<h3 class="anchored" data-anchor-id="data-visualisation">Data Visualisation</h3>
<p>Great. Now we have the data in the desired format, we need to plot the data to see if a general trend is present</p>
<p>We will use ggplot (as we have done before) to create a scatterplot of mean anxiety on the x-axis and n_weeks on the y-axis. You actually used almost identical code to create this in <a href="https://m1v0.github.io/FASS512/Worksheets/Worksheet_wk8.html#conducting-a-correlation">week 8 - Conducting a correlation</a></p>
<p>It should look like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">|&gt;</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(mean_anxiety, n_weeks)) <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Worksheet_wk9_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>What does this general trend show us? What do we see as a relationship in the data?</p>
</section>
<section id="conducting-a-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="conducting-a-linear-regression">Conducting a linear regression</h3>
<p>Now we have tidied the data and visualised what we want to do, we can run the regression. We tidy the data to get it into the format required for the regression, and we plot the data to check some of the assumptions (linearity), and to see whether the data is suitable for regression modelling.</p>
<p>For linear regression we will use the function <code>lm()</code> which stands for linear model. It comes from base R and is commonly used for a lot of things. We use the same kind of syntax we used before in analysis <code>DV ~ IV</code>.</p>
<p>We run a linear regression using the following code to predict the anxiety from the number of weeks. So we want to know if increased attendance significantly reduces anxiety.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>model_stars <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean_anxiety <span class="sc">~</span> n_weeks, data)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_stars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean_anxiety ~ n_weeks, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.96605 -0.29900 -0.08293  0.32864  1.03414 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.61215    0.17402  15.010  &lt; 2e-16 ***
n_weeks     -0.11746    0.03392  -3.463  0.00143 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4929 on 35 degrees of freedom
Multiple R-squared:  0.2552,    Adjusted R-squared:  0.2339 
F-statistic: 11.99 on 1 and 35 DF,  p-value: 0.001428</code></pre>
</div>
</div>
<p>Great, we have a summary of our regression analysis, and now we need to extract the relevant information from it. The output should look familiar to the t-test and correlation output from last session. I go through an example of this in this session’s lecture material for understanding an interpretation.</p>
<p>Answer the following questions based on the output</p>
<ol type="1">
<li>The estimate of the y-intercept for the model, rounded to two decimal places, is <input class="webex-solveme nospaces" size="4" data-answer="[&quot;2.61&quot;]"></li>
<li>To three decimal places, if the GLM for this model is y = mX=C, what is m? <input class="webex-solveme nospaces" size="5" data-answer="[&quot;-0.12&quot;,&quot;-.12&quot;]"></li>
<li>To three decimal places, for each additional week attended, mean anxiety <select class="webex-select"><option value="blank"></option><option value="answer">decreases</option><option value="">increases</option></select> by <input class="webex-solveme nospaces" size="4" data-answer="[&quot;0.12&quot;,&quot;.12&quot;]"></li>
<li>To two decimal places, what is the overall F-ratio of the model? <input class="webex-solveme nospaces" size="5" data-answer="[&quot;11.99&quot;]"></li>
<li>Is the overall model significant? <select class="webex-select"><option value="blank"></option><option value="answer">yes</option><option value="">cannot tell</option><option value="">no</option></select></li>
<li>What proportion of the variance does the model explain (to 2dp)? <input class="webex-solveme nospaces" size="5" data-answer="[&quot;23.39&quot;]"></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>In the summary table, this is the estimate of the intercept. 2.In the summary table, this is the estimate of mean_anxiety, i.e., the slope. 3.In the summary table, this is also the estimate of mean_anxiety, the slope is how much it decreases so you just remove the - sign.</li>
<li>In the summary table, the F-ratio is noted as the F-statistic.</li>
<li>The overall model p.value is .001428 which is less than .05, therefore significant.</li>
<li>The variance explained is determined by R-squared, you simply multiple it by 100 to get the percent. You should always use the adjusted R-squared value.</li>
</ol>
</div>
</div>
</div>
<p>Cool. Before we move on, let’s look at the interpretation of the model, and specifically question 3 here. We say that the mean anxiety for those who attend no weeks is the same as the Y intercept (the answer to Q1), but for each week attended, anxiety <select class="webex-select"><option value="blank"></option><option value="answer">decreases by .12</option></select>. Hopefully you see how we interpret this from the data that we have.</p>
</section>
<section id="checking-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="checking-assumptions">Checking assumptions</h3>
<p>Recall from the lecture that we cannot check the assumptions until we have our model residuals. It seems a bit backwards, create a model and check whether we can run the model, but that’s how it works unfortunately. The assumptions are</p>
<ol type="1">
<li>The outcome/DV is a interval/ratio level data</li>
<li>The predictor variable is interval/ratio or categorical (with two levels)</li>
<li>All values of the outcome variable are independent (i.e., each score should come from a different participant)</li>
<li>The predictors have non-zero variance</li>
<li>The relationship between outcome and predictor is linear</li>
<li>The residuals should be normally distributed</li>
<li>There should be homoscedasticity (homogeneity of variance, but for the residuals)</li>
</ol>
<p>Assumptions 1-3 are straightforward. We know this from the data we have and the design of the study. Assumption 4 simply means that there is some spread in the data - for example, there’s no point running a regression with age as a variable if all your participants are 20 years old. We can check this using the scatterplot we created already and we can see that this assumption is met. Phew!</p>
<p>For the rest of the assumptions, we’re going to use functions from the packages <code>performance</code> that make life a whole lot easier. We will use a package to do the assumption visualisations for us called <code>performance</code> which is quite handy. So first, install and load <code>performance</code>.</p>
<p>We specifically want <code>check_model()</code> from <code>performance</code> and it is run as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(model_stars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Worksheet_wk9_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Looking at the plots (you may wish to zoom into it for easier viewing), it even tells us what we are wanting to look for. All of them look okay, for Assumption 5, linearity, the plot suggests it’s not perfect but it looks good enough.</p>
<p>For Assumption 6, normality of residuals, the plot does suggest that the residuals might be normal, but we can double check this with <code>check_normality()</code> which runs a Shapiro-Wilk test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(model_stars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.625).</code></pre>
</div>
</div>
<p>For homoscedasticity, the plot looks mostly fine, but we can double check this with <code>check_heteroscedasticity()</code> and the result confirms that the data have met this assumption.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(model_stars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.301).</code></pre>
</div>
</div>
<p>Great. So we can be content that the model we created is suitable. It meets the assumptions and tests our hypothesis appropriately. Let us move on to the next step, determining the effect size. We did this for chi-squared and t-tests, anovas above, so let us conduct one for a linear regression too.</p>
</section>
<section id="effect-sizes" class="level3">
<h3 class="anchored" data-anchor-id="effect-sizes">Effect sizes</h3>
<p>For a linear regression, we can use Cohen’s f<sup>2</sup> (Selya, 2012)<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> which is calculated through <span class="math inline">\(F^2 = R^2/(1-R^2)\)</span>. We have to calculate this ourselves which is relatively trivial.</p>
<p>We first want to extract the R<sup>2</sup> value from our model (making sure it is the adjusted one)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>model_stars_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_stars) <span class="co"># save to an object</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>r2 <span class="ot">&lt;-</span> model_stars_summary<span class="sc">$</span>adj.r.squared <span class="co">#extract the relevant value</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>r2<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>r2) <span class="co">#compute f2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3053367</code></pre>
</div>
</div>
<p>According to Cohen’s (1988)<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> guidelines, f<sup>2</sup> ≥ 0.02, f<sup>2</sup> ≥ 0.15, and f<sup>2</sup> ≥ 0.35 represent small, medium, and large effect sizes, respectively.</p>
<p>So what size effect do we have? <select class="webex-select"><option value="blank"></option><option value="">small</option><option value="answer">medium</option><option value="">large</option></select></p>
</section>
<section id="writing-up-a-linear-regression-result" class="level3">
<h3 class="anchored" data-anchor-id="writing-up-a-linear-regression-result">Writing up a linear regression result</h3>
<p>Okay, wow. We’ve done a lot of computation to get to this point. It is all worthless if we cannot articulate it in a meaningful manner for our dear reader. We want to revisit our <code>descriptives</code> object for means and SDs, our model output in <code>model_stars_summary</code>, and the effect size we calculated. For APA formatting, we report all values to 2 decimal places, except for p-values which are 3dp, unless it is under .001, then we report &lt;.001. Some of the values are filled in for you.</p>
<p>A simple linear regression was conducted to determine whether statistics anxiety (mean = <input class="webex-solveme nospaces" size="4" data-answer="[&quot;2.08&quot;]">, SD = <input class="webex-solveme nospaces" size="4" data-answer="[&quot;0.56&quot;,&quot;.56&quot;]">) was predicted via attendance of drop-in sessions (mean = 4.54, SD = 2.42). The regression found a significant decrease in mean anxiety, F(1, 35) = <input class="webex-solveme nospaces" size="5" data-answer="[&quot;11.99&quot;]">, <em>p</em> = .001, R<sup>2</sup><sub>adj</sub> = <input class="webex-solveme nospaces" size="4" data-answer="[&quot;0.23&quot;,&quot;.23&quot;]">, f<sup>2</sup> = <input class="webex-solveme nospaces" size="4" data-answer="[&quot;0.31&quot;,&quot;.31&quot;]">, accounting for <input class="webex-solveme nospaces" size="2" data-answer="[&quot;23&quot;]">% of variance. Attendance was a significant predictor (β = -.12, p = 0.001.)</p>
</section>
</section>
<section id="task-4-proof-anova-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="task-4-proof-anova-linear-regression">Task 4: Proof: ANOVA == Linear Regression</h2>
<p>Using the same data as the robot ANOVA</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>model_robot_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Score <span class="sc">~</span> Group, robot)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>model_robot_lm_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_robot_lm)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>model_robot_lm_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Score ~ Group, data = robot)

Residuals:
     Min       1Q   Median       3Q      Max 
-20.3625  -4.6000  -0.2313   4.9000  15.4000 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  58.1000     0.7812  74.372  &lt; 2e-16 ***
GroupB        2.2625     1.1048   2.048   0.0417 *  
GroupO        5.5000     1.1048   4.978 1.23e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.987 on 237 degrees of freedom
Multiple R-squared:  0.09557,   Adjusted R-squared:  0.08794 
F-statistic: 12.52 on 2 and 237 DF,  p-value: 6.768e-06</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(model_robot_lm_summary<span class="sc">$</span>fstatistic[[<span class="dv">1</span>]], <span class="dv">4</span>) <span class="sc">==</span> <span class="fu">round</span>(<span class="fu">summary</span>(model_robot)[[<span class="dv">1</span>]][[<span class="st">"F value"</span>]][[<span class="dv">1</span>]], <span class="dv">4</span>) <span class="co">#excuse what looks messy, but if you decipher what I have written, I have extracted the F-value from both the original model (on the right) and the linear model (on the left) and tested their equivalence. It returns true because they are the exact same number</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>I won’t prove all the other numbers are the same, you can do that by looking at the summary outputs</p>
<p>But posthoc values are computed using emmeans like below. Check that the values are the same as in the ANOVA output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(model_robot_lm, pairwise <span class="sc">~</span> Group)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 Group emmean    SE  df lower.CL upper.CL
 A       58.1 0.781 237     56.6     59.6
 B       60.4 0.781 237     58.8     61.9
 O       63.6 0.781 237     62.1     65.1

Confidence level used: 0.95 

$contrasts
 contrast estimate  SE  df t.ratio p.value
 A - B       -2.26 1.1 237  -2.048  0.1032
 A - O       -5.50 1.1 237  -4.978  &lt;.0001
 B - O       -3.24 1.1 237  -2.930  0.0103

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(model_robot, pairwise <span class="sc">~</span> Group)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 Group emmean    SE  df lower.CL upper.CL
 A       58.1 0.781 237     56.6     59.6
 B       60.4 0.781 237     58.8     61.9
 O       63.6 0.781 237     62.1     65.1

Confidence level used: 0.95 

$contrasts
 contrast estimate  SE  df t.ratio p.value
 A - B       -2.26 1.1 237  -2.048  0.1032
 A - O       -5.50 1.1 237  -4.978  &lt;.0001
 B - O       -3.24 1.1 237  -2.930  0.0103

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>Because we used <code>emmeans</code> rather than <code>pairwise_t_tests</code> (the latter won’t work on <code>lm()</code>) we get different outputs from the ANOVA section above, due to differences in how things are calculated. But we see we get the same numbers if we run emmeans here on both. Note that despite differences between <code>emmeans</code> and <code>pairwise_t_tests</code> the same interpretation would be made.</p>
<p>Ta-da! ANOVA is a linear regression, just masked. My advice is to use linear regressions in your own work, but know what an ANOVA is in case someone asks for one (in which case do it using lm anyway) or you come across one in a paper.</p>
</section>
<section id="other" class="level2">
<h2 class="anchored" data-anchor-id="other">Other</h2>
<section id="the-trout-anova-example-from-the-slides" class="level3">
<h3 class="anchored" data-anchor-id="the-trout-anova-example-from-the-slides">The trout ANOVA example from the slides</h3>
<p>Data is simulated using Fry and Cox (1970) as a basis<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">0603</span>) <span class="co">#set the seed for replicability</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="co">#generate some data, with length sampled from the normal distribution</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>trout <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">waterspeed =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"fast"</span>, <span class="dv">20</span>), <span class="fu">rep</span>(<span class="st">"slow"</span>, <span class="dv">20</span>), <span class="fu">rep</span>(<span class="st">"very slow"</span>, <span class="dv">20</span>)),</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">length =</span> <span class="fu">c</span>(<span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">50</span>, <span class="dv">10</span>), <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">60</span>, <span class="dv">10</span>), <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">65</span>, <span class="dv">10</span>))</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> </span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">length =</span> <span class="fu">round</span>(length, <span class="dv">2</span>))</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>trout</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 60 × 2
   waterspeed length
   &lt;chr&gt;       &lt;dbl&gt;
 1 fast         66.5
 2 fast         46.5
 3 fast         49.0
 4 fast         59.4
 5 fast         52.2
 6 fast         77.0
 7 fast         44.8
 8 fast         39.6
 9 fast         49.3
10 fast         71.7
# ℹ 50 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>trout <span class="sc">|&gt;</span> </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(waterspeed, length)) <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Worksheet_wk9_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(length <span class="sc">~</span> waterspeed, trout) <span class="sc">|&gt;</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
waterspeed   2   1839   919.5   8.911 0.000429 ***
Residuals   57   5881   103.2                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">effectsize</span>(<span class="fu">aov</span>(length <span class="sc">~</span> waterspeed, trout))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>For one-way between subjects designs, partial eta squared is equivalent
  to eta squared. Returning eta squared.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA

Parameter  | Eta2 |       95% CI
--------------------------------
waterspeed | 0.24 | [0.08, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise_t_test</span>(trout,</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  length <span class="sc">~</span> waterspeed, <span class="co"># indicate this is paired (within participants) data</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span> <span class="co">#adjust for bonferroni correction</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 9
  .y.    group1 group2       n1    n2        p p.signif    p.adj p.adj.signif
* &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;     &lt;int&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;       
1 length fast   slow         20    20 0.384    ns       1        ns          
2 length fast   very slow    20    20 0.000176 ***      0.000527 ***         
3 length slow   very slow    20    20 0.0027   **       0.00809  **          </code></pre>
</div>
</div>
<p>The bigger the fish, the slower it can swim. So smaller sized fish are more suitable for faster currents as they are not swept away.</p>
</section>
<section id="the-house-regression-example" class="level3">
<h3 class="anchored" data-anchor-id="the-house-regression-example">The house regression example</h3>
<p>The market historical data set of real estate valuation are collected from Sindian Dist., New Taipei City, Taiwan</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>houses <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Real estate.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 414 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (8): ID, transaction_date, house_age, distance_MRT, convenience_store_co...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>houses<span class="sc">$</span>unit_price <span class="sc">|&gt;</span> <span class="fu">hist</span>() <span class="co"># looks mostly normal (one very high house price)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Worksheet_wk9_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>houses_filt <span class="ot">&lt;-</span> houses <span class="sc">|&gt;</span> <span class="fu">filter</span>(unit_price <span class="sc">&lt;</span> <span class="dv">90</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="co">#can we use house_age as a predictor? It isn't a linear relationship, so no</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>houses_filt <span class="sc">|&gt;</span> </span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(house_age, unit_price)) <span class="sc">+</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Worksheet_wk9_files/figure-html/unnamed-chunk-32-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co">#number of shops is more linear</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>houses_filt <span class="sc">|&gt;</span> </span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(convenience_store_count, unit_price)) <span class="sc">+</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Worksheet_wk9_files/figure-html/unnamed-chunk-32-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(unit_price <span class="sc">~</span> convenience_store_count, houses_filt) <span class="sc">|&gt;</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = unit_price ~ convenience_store_count, data = houses_filt)

Residuals:
    Min      1Q  Median      3Q     Max 
-35.339  -7.098  -1.398   6.002  30.661 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              26.6567     0.8717   30.58   &lt;2e-16 ***
convenience_store_count   2.7138     0.1727   15.71   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 10.32 on 411 degrees of freedom
Multiple R-squared:  0.3753,    Adjusted R-squared:  0.3738 
F-statistic: 246.9 on 1 and 411 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#effect size</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fl">0.3738</span><span class="sc">/</span>(<span class="dv">1</span><span class="fl">-0.3738</span>) <span class="co">#compute f2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5969339</code></pre>
</div>
</div>


</section>
</section>


<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Cruise, R. J., Cash, R. W., &amp; Bolton, D. L. (1985). Development and validation of an instrument to measure statistical anxiety. Proceedings of the American Statistical Association, Section on Statistical Education, Las Vegas, NV.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Selya, A. S., Rose, J. S., Dierker, L. C., Hedeker, D., &amp; Mermelstein, R. J. (2012). A practical guide to calculating Cohen’sf 2, a measure of local effect size, from PROC MIXED. Frontiers in psychology, 3, 111.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Cohen J. E. (1988). Statistical Power Analysis for the Behavioral Sciences. Hillsdale, NJ: Lawrence Erlbaum Associates, Inc<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Fry, F. E. J., &amp; Cox, E. T. (1970). A relation of size to swimming speed in rainbow trout. Journal of the Fisheries Board of Canada, 27(5), 976-978.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../Worksheets/Worksheet_wk8.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">8. Correlations and t-tests</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../Worksheets/Answers/Worksheet_wk1_Answers.html" class="pagination-link">
        <span class="nav-page-text">1. Introduction to quantitative research methods using R - Answers</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Website developed by Matthew Ivory</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/M1V0/FASS512">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://modules.lancaster.ac.uk/course/view.php?id=41149">
      <i class="bi bi-file-earmark-slides" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>